FROM openjdk:17
LABEL maintainer="javaguides.net"
COPY target/spring-boot-data-jpa-0.0.1-SNAPSHOT.jar spring-boot-data-jpa-0.0.1-SNAPSHOT.jar
CMD [ "java", "-jar", "spring-boot-data-jpa-0.0.1-SNAPSHOT.jar"]